### ISSUE TITLE
Cannot import "House"

### ISSUE THREAD

**Issue by ppwwyyxx** [HoME-Platform/home-platform#1]
```
question-gen/preprocess.py
4:from home_platform.core import House

samples/overview/generateFigures.py
33:from home_platform.core import House, Agent, Object

tests/experiments/agent-in-house.py
5:from home_platform.core import House, Agent

samples/walk/randomWalk.py
35:from home_platform.core import House

tests/experiments/agent-in-house2.py
6:from home_platform.core import House, Agent

tests/benchmarks/benchmark.py
31:from home_platform.core import House
```
They all failed because core.py has no `House`

**Comment by ankeshanand** [comment]
Hi @ppwwyyxx, Looks like we forgot to update examples after refactoring the core classes. Expect a fix soon!

**Comment by TsunHsuang-Wang** [comment]
seems like home_platform/core.py is incomplete

**Comment by fgolemo** [comment]
@ppwwyyxx & @TsunHsuang-Wang 
Should be fixed now. Could you guys have another look please?
The core.py file wasn't incomplete - this was just some leftover from refactoring. Thanks for finding the occurances.

**Comment by cclauss** [comment]
Why are the Travis test green when one test still fails?
* https://travis-ci.org/HoME-Platform/home-platform/jobs/311430979#L3977

**Comment by fgolemo** [comment]
@cclauss that's a really good question. I'll look into this this week (opened a separate issue). I think in general the run_tests.sh script should return exit code 1 if there were any issues.

Something like 
```
if [[ has_error -eq 1 ]]; then
    exit 1
fi
```
at the end.

**Comment by cclauss** [comment]
Yes.  See #12 but it did not work.  :-(
